controller_list:
  - name: fingers_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - aa1
      - act1
      - mcp1
      - pip1
      - dip1
      - aa2
      - act2
      - mcp2
      - pip2
      - dip2
      - aa3
      - act3
      - mcp3
      - pip3
      - dip3
      - aa4
      - act4
      - mcp4
      - pip4
      - dip4